apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-realms-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/keycloak-realms
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gluster-hostpath
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-master-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-realms-pvc
  namespace: shopnow
spec:
  volumeName: keycloak-realms-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gluster-hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-keycloak-realms-deployment
  namespace: shopnow
  labels:
    app: shopnow-keycloak-realms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopnow-keycloak-realms
  template:
    metadata:
      labels:
        app: shopnow-keycloak-realms
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master-2
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.3
          imagePullPolicy: IfNotPresent
          command:
            - "/opt/keycloak/bin/kc.sh"
          args:
            - "start-dev"
            - "--import-realm"
          env:
            - name: KC_DB
              value: mysql
            - name: KC_DB_URL
              value: jdbc:mysql://shopnow-keycloak-mysql-service:3306/keycloak?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: password
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HOSTNAME
              value: keycloak-shopnow.devopseduvn.live
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: edge
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-realms
              readOnly: true
      volumes:
        - name: keycloak-realms
          persistentVolumeClaim:
            claimName: keycloak-realms-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shopnow-keycloak-realms-service
  namespace: shopnow
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: shopnow-keycloak-realms
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnow-keycloak-realms-ingress
  namespace: shopnow
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  ingressClassName: nginx
  rules:
    - host: keycloak-shopnow.pma-server.site
      http:
        paths:
          - backend:
              service:
                name: shopnow-keycloak-realms-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
