apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    app: vault
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/vault
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: glusterfs-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-master-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv1
  labels:
    app: vault
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/vault1
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: glusterfs-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-master-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv2
  labels:
    app: vault
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/vault2
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: glusterfs-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-master-2
